version: '3.8'

services:
  auth-service:
    build: ./auth-service
    ports:
      - "3000:3000"
    networks:
      - microservices-network

  product-service:
    build: ./product-service
    ports:
      - "5000:5000"
    networks:
      - microservices-network

  order-service:
    build: ./order-service
    ports:
      - "8080:8080"
    networks:
      - microservices-network

  payment-service:
    build: ./payment-service
    ports:
      - "8000:8000"
    networks:
      - microservices-network

  postgres-db:
    image: postgres:13
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - microservices-network

  mongodb:
    image: mongo:4.4
    volumes:
      - mongo-data:/data/db
    networks:
      - microservices-network

  mysql-db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: payment_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - microservices-network

networks:
  microservices-network:

volumes:
  postgres-data:
  mongo-data:
  mysql-data:

   

